services:
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: .
    ports:
      - "${EXPRESS_PORT}:3000"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: ${MARIADB_DATABASE}
      DB_USER: root
      DB_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      EXPRESS_PORT: ${EXPRESS_PORT}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:
