name: CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: ${{ secrets.MARIADB_PASSWORD_CI }}
      DB_NAME: devops_tp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mon-app .

      - name: Start MariaDB container
        run: |
          docker run -d --name mariadb -e MARIADB_ROOT_PASSWORD=${{ secrets.MARIADB_PASSWORD_CI }} -e MARIADB_DATABASE=devops_tp -p 3306:3306 mariadb:11
          # Attendre que MariaDB soit prêt (healthcheck ou boucle)
          for i in {1..30}; do
            if docker exec mariadb mariadb-admin ping --silent; then
              echo "MariaDB container is up!"
              break
            fi
            echo "Waiting for MariaDB container..."
            sleep 2
          done

      - name: Start app container (avec lien au container mariadb)
        run: |
          docker run -d --name mon-app --link mariadb:mariadb \
            -e DB_HOST=mariadb \
            -e DB_USER=root \
            -e DB_PASSWORD=${{ secrets.MARIADB_PASSWORD_CI }} \
            -e DB_NAME=devops_tp \
            -p 3000:3000 mon-app
          # Attendre que l'app soit prête (optionnel : healthcheck custom ou pause)
          sleep 10

      - name: Cleanup containers
        run: |
          docker stop mon-app mariadb
          docker rm mon-app mariadb
