name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy on remote server
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 89.168.46.10 >> ~/.ssh/known_hosts

    - name: Merge and Deploy on Sandbox VM
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@89.168.46.10 << 'EOF'
          set -e
          cd ESGI/CI_CD/project-devops/

          git fetch --all
          git reset --hard origin/main

          echo "Deploying latest code"
          docker compose up -d
        EOF
