name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services
        run: docker compose up -d --build
        env:
          EXPRESS_PORT: 3000
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: devops_project
          DB_USER: root
          DB_PASSWORD: ${{ secrets.MARIADB_PASSWORD_CI }}
          ADMIN_USER: admin
          ADMIN_PASSWORD: password
          MARIADB_ROOT_PASSWORD: ${{ secrets.MARIADB_PASSWORD_CI }}
          MARIADB_DATABASE: devops_project

      - name: Wait for MariaDB to be healthy
        run: |
          for i in {1..30}; do
            if docker compose exec -T mariadb mariadb-admin ping -h localhost --silent; then
              echo "MariaDB is up!"
              break
            fi
            echo "Waiting for MariaDB..."
            sleep 2
          done

      - name: Setup database with fixtures
        run: docker compose exec -T app node fixtures/setup-db.js

      - name: Run linter
        run: docker compose exec -T app npm run lint

      - name: Run unit tests
        run: docker compose exec -T app npm run test:unit
        env:
          ADMIN_USER: admin
          ADMIN_PASSWORD: password

      - name: Run e2e tests
        run: npx cypress run

      - name: Show logs if failed
        if: failure()
        run: docker compose logs

      - name: Stop containers
        if: always()
        run: docker compose down -v