name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MARIADB_PASSWORD_CI }}
          MYSQL_DATABASE: devops_tp
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASSWORD: ${{ secrets.MARIADB_PASSWORD_CI }}
      DB_NAME: devops_tp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Wait for MariaDB to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -u root --password=${{ secrets.MARIADB_PASSWORD_CI }} --silent; then
              echo "MariaDB is up!"
              break
            fi
            echo "Waiting for MariaDB..."
            sleep 2
          done

      - name: Setup database with fixtures
        run: node fixtures/setup-db.js
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: ${{ secrets.MARIADB_PASSWORD_CI }}
          DB_NAME: devops_tp

      - name: Run unit tests
        run: npm run test

      # Démarrer le serveur pour E2E
      - name: Start server for e2e tests
        run: node src/app.js &
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: ${{ secrets.MARIADB_PASSWORD_CI }}
          DB_NAME: devops_tp

      - name: Run Cypress tests
        run: npx cypress run --browser chrome --headless
